[package]
name = "food_puzzle"
version = "0.5.0"
edition = "2021"
authors=["{{llesha}}"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3", features = ["console"] }